# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 12345678
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: doctor_care_development

test:
  <<: *default
  database: project_mysql_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: project_mysql_production
  username: project_mysql
  password: <%= ENV['PROJECT_MYSQL_DATABASE_PASSWORD'] %>
